### PR TITLE
Updated documentation and system diagrams

### PR DESCRIPTION
**Pull request by ethax-ross**
[Trello-2681](https://trello.com/c/RzwGp03i/2681-up-to-date-architecture-diagrams)

- Fix markdown formatting and restore links

The Markdown formatting was a bit off on some of these. Also restores some links that were in the Confluence docs these were migrated from.

- Add architecture documentation

Add an architecture document that includes a system diagram of the Get into Teaching systems. I'm not sure the best place for this to live, but we seem to bunch other things that are GiT-wide into the API repo so it probably makes sense for now.

Uses [diagrams.net](https://diagrams.net) - import `architecture.drawio` to modify.

---

architecture

### CODE REVIEW

**Review by jkempster34 — COMMENTED** [review]
This looks cool and imported fine in diagrams.net. Just wondering if this part looks like the apps are sharing the same databases, rather than the diagram just reusing the symbol? 

image

**Comment by ethax-ross** [comment]
@jkempster34 the apps do share the same Postgres instance; I think it was a faff/expensive to have multiple high-availability Postgres instances so the way its setup they all share the same one, albeit using different databases for Postgres and namespaces for Redis

**Review by jkempster34 — APPROVED** [review]
> @jkempster34 the apps do share the same Postgres instance; I think it was a faff/expensive to have multiple high-availability Postgres instances so the way its setup they all share the same one, albeit using different databases for Postgres and namespaces for Redis

Didn't know that! Don't know if it is worth adding GOV Notify and Google Geocoding to School Experience too, but looks nice 💯

**Comment by ethax-ross** [comment]
Ah yeah that's a good shout, I'll get this merged down then do that as another PR later on

**Pull request merged**
